<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shivraj" failures="1" tests="2" name="Test2" time="43.427" errors="0" timestamp="2021-07-11T18:31:22 CEST">
  <testcase classname="com.nopCommerceProjectV1.testCases.TC_LoginTest_001" name="loginTest" time="22.716"/>
  <testcase classname="com.nopCommerceProjectV1.testCases.TC_LoginTest_001" name="loginTestFail" time="13.191">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.nopCommerceProjectV1.testCases.TC_LoginTest_001.loginTestFail(TC_LoginTest_001.java:72)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginTestFail -->
</testsuite> <!-- Test2 -->
